CREATE TABLE users (id SERIAL PRIMARY KEY, email VARCHAR(90) NOT NULL, password VARCHAR(60) NOT NULL)
CREATE TABLE spaces (id SERIAL PRIMARY KEY, name VARCHAR(100) NOT NULL, description TEXT NOT NULL, price NUMERIC NOT NULL, user_id INTEGER REFERENCES users(id))
CREATE TABLE available_dates (id SERIAL PRIMARY KEY, space_id INTEGER REFERENCES spaces(id) NOT NULL, date DATE NOT NULL)
CREATE TABLE booking_requests (id SERIAL PRIMARY KEY, space_id INTEGER NOT NULL REFERENCES spaces(id), guest_id INTEGER REFERENCES users(id) NOT NULL, date DATE NOT NULL);